Ramdom
WildCodeSchool/tlse0321-js-p2-pokewildex pull request #50
Opened 2021-04-21 09:20 UTC by thomas31toulouse

2021-04-21 09:23 UTC, AnthonyDeplanque approved these changes
Yes !

2021-04-21 09:27 UTC, gwen31 approved these changes
Good

2021-04-21 10:13 UTC, Froyj requested changes

2021-04-21 10:13 UTC, Froyj commented on src/Components/RandomTeam.jsx
> +
import la fonction depuis un autre fichier, definir maxId et minId dans un fichier a part dans un dossier "constants"

2021-04-21 10:13 UTC, Froyj commented on src/Components/RandomTeam.jsx
> +
renommer fonction (par exemple : getRandomPokemonId)

2021-04-21 11:50 UTC, thomas31toulouse commented
toute les modifications demandées ont été faite

2021-04-22 12:48 UTC, Froyj approved these changes

2021-04-22 12:49 UTC, merged