Color types
WildCodeSchool/tlse0321-js-p2-pokewildex pull request #66
Opened 2021-04-28 09:51 UTC by AnthonyDeplanque

2021-04-28 09:53 UTC, gwen31 approved these changes

2021-04-28 09:55 UTC, ChloeMoreno approved these changes
wow bg

2021-04-28 09:55 UTC, thomas31toulouse approved these changes
beau travail

2021-04-28 10:51 UTC, Froyj requested changes

2021-04-28 10:51 UTC, Froyj commented on src/Components/PokedexDetails.jsx
> +  }
encapsule tout ca dans un useEffect qui observera types via le tableau de dependances, tu auras aussi besoin de gerer typesForCard et colorsForCard via le state pour que ca marche. Ca nous permettra de s'assurer que la valeur pour ces variable est définie dans tous les cas d'utilisation du composant PokedexDetails (eventuellement si on veut le reutiliser dans un endroit on ou est pas sur que types est correctement envoyé)

2021-04-28 14:59 UTC, AnthonyDeplanque commented
J'ai supprimé typesForCard qui ne nous servait plus à rien pour le requêtage de la couleur.

2021-04-29 08:22 UTC, AnthonyDeplanque commented on src/Components/PokedexDetails.jsx
> +      }
Le useState (colorsforcard) remplace ici les variables précédentes; typesforcard ne sert plus à rien.
le setter a été mis à l'intérieur d'un useEffect;

2021-04-29 08:24 UTC, AnthonyDeplanque commented on src/Components/PokedexDetails.jsx
> +  }, [pokemonId]);
suppression de l'import PokemonFetchApi, pour remettre le useEffect dans le component.

2021-04-29 11:23 UTC, Froyj requested changes
Il manque toujours des trucs :p on en parle directement plus tard
```
const pokemonInfos = PokemonFetchApi(pokemonId);
  const {
    id, sprites, types, abilities, species,
  } = pokemonInfos;
``` doit aussi etre prsent dans le useEffect et la variable a obsrver est bien pokemonId, pas pokemon si tu veux plus d'explication on en parle plus tard (apres le talk)

2021-04-29 14:56 UTC, Froyj approved these changes

2021-04-29 14:57 UTC, merged